spring:
  mail:
    host: mailpit
    port: 1025
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

app:
  mail:
    enabled: true
